
  # Build Options:

set(WITH_BULLET OFF CACHE BOOL "" FORCE)


set(WITH_CYCLES OFF CACHE BOOL "" FORCE)
set(WITH_FFTW3 OFF CACHE BOOL "" FORCE)

set(WITH_FREESTYLE OFF CACHE BOOL "" FORCE)
set(WITH_GMP OFF CACHE BOOL "" FORCE)
set(WITH_HARU OFF CACHE BOOL "" FORCE)


set(WITH_IK_ITASC OFF CACHE BOOL "" FORCE)
set(WITH_IK_SOLVER OFF CACHE BOOL "" FORCE)
set(WITH_INPUT_NDOF OFF CACHE BOOL "" FORCE)
set(WITH_INPUT_IME OFF CACHE BOOL "" FORCE)
set(WITH_INTERNATIONAL OFF CACHE BOOL "" FORCE)
set(WITH_MANIFOLD OFF CACHE BOOL "" FORCE)


set(WITH_OPENCOLORIO OFF CACHE BOOL "" FORCE)
set(WITH_OPENIMAGEDENOISE OFF CACHE BOOL "" FORCE)
set(WITH_OPENIMAGEIO OFF CACHE BOOL "" FORCE)
set(WITH_OPENSUBDIV OFF CACHE BOOL "" FORCE)
set(WITH_OPENVDB OFF CACHE BOOL "" FORCE)
set(WITH_POTRACE OFF CACHE BOOL "" FORCE)
set(WITH_PUGIXML OFF CACHE BOOL "" FORCE)
set(WITH_QUADRIFLOW OFF CACHE BOOL "" FORCE)
set(WITH_TBB OFF CACHE BOOL "" FORCE)


set(WITH_MATERIALX OFF CACHE BOOL "" FORCE)
set(WITH_XR_OPENXR OFF CACHE BOOL "" FORCE)


  # 3D format
  set(WITH_ALEMBIC OFF CACHE BOOL "" FORCE)
  set(WITH_USD OFF CACHE BOOL "" FORCE)
  set(WITH_IO_WAVEFRONT_OBJ OFF CACHE BOOL "" FORCE)
  set(WITH_IO_PLY OFF CACHE BOOL "" FORCE)
  set(WITH_IO_STL OFF CACHE BOOL "" FORCE)
  set(WITH_IO_FBX OFF CACHE BOOL "" FORCE)
  set(WITH_IO_GREASE_PENCIL OFF CACHE BOOL "" FORCE)
  
# UV solvers.
  set(WITH_UV_SLIM OFF CACHE BOOL "" FORCE)



set(WITH_FFMPEG OFF CACHE BOOL "" FORCE)
set(WITH_OPENAL OFF CACHE BOOL "" FORCE)
set(WITH_OSL OFF CACHE BOOL "" FORCE)



  # Compiler Options:
set(WITH_BUILDINFO OFF CACHE BOOL "" FORCE)
set(WITH_OPTIMIZED_BUILD_TOOLS OFF CACHE BOOL "" FORCE)

  # System Options:
set(WITH_MEM_JEMALLOC OFF CACHE BOOL "" FORCE)

  # Image Formats:
set(WITH_IMAGE_CINEON OFF CACHE BOOL "" FORCE)
set(WITH_IMAGE_OPENEXR OFF CACHE BOOL "" FORCE)
set(WITH_IMAGE_OPENJPEG OFF CACHE BOOL "" FORCE)
set(WITH_IMAGE_WEBP OFF CACHE BOOL "" FORCE)



  # Audio:
set(WITH_AUDASPACE OFF CACHE BOOL "" FORCE)
set(WITH_RUBBERBAND OFF CACHE BOOL "" FORCE)
set(WITH_CODEC_FFMPEG OFF CACHE BOOL "" FORCE)
set(WITH_CODEC_SNDFILE OFF CACHE BOOL "" FORCE)
set(WITH_WASAPI OFF CACHE BOOL "" FORCE)
  
  


  # Python:
  # - WITH_PYTHON_INSTALL             ON
set(WITH_PYTHON_INSTALL_NUMPY OFF CACHE BOOL "" FORCE)
set(WITH_PYTHON_INSTALL_ZSTANDARD OFF CACHE BOOL "" FORCE)

  

  # Modifiers:
set(WITH_MOD_FLUID OFF CACHE BOOL "" FORCE)
set(WITH_MOD_OCEANSIM OFF CACHE BOOL "" FORCE)
set(WITH_MOD_REMESH OFF CACHE BOOL "" FORCE)

  # Rendering
set(WITH_HYDRA OFF CACHE BOOL "" FORCE)

# Compression
set(WITH_DRACO OFF CACHE BOOL "" FORCE)

# Camera/motion tracking
set(WITH_LIBMV OFF CACHE BOOL "" FORCE)
set(WITH_LIBMV_SCHUR_SPECIALIZATIONS OFF CACHE BOOL "" FORCE)